teste.tag : teste.txt
	linguakit tagger pt -nec teste.txt > teste.tag

Camilo-Amor_de_Perdicao.tag : Camilo-Amor_de_Perdicao.txt
	linguakit tagger pt -nec Camilo-Amor_de_Perdicao.txt > Camilo-Amor_de_Perdicao.tag